name: "🐛 Bug report"
description: Reporta un fallo con pasos reproducibles
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - Onboarding
        - Login
        - Home
        - Session/Persistencia
        - Networking
        - UI/UX
        - Otro
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Lista numerada (1,2,3...) y lo más precisa posible.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Entorno
      placeholder: "iOS 18.x, iPhone 15 Pro (sim/device), versión app, commit SHA"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Capturas
      description: Pega logs relevantes o adjunta imágenes.
